// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:jsgen`.
// ignore_for_file: type=lint
import '' as self;

/// Bindings to `headers/example.h`.
import 'dart:typed_data';
import 'dart:js_interop';
import 'dart:js_interop_unsafe';

///
/// Sub-classes of [NativeType] represent a "native" type (by which we mean a
/// type that can be passed to a WASM-compiled native function), and its
/// equivalent Dart representation.
///
/// Most sub-classes are non-constructible; they are only intended to preserve
/// compile-time type information and to translate between native types and
/// their Dart equivalent.
///
/// The exceptions are [Pointer], [Array] and sub-classes of [Struct]; these can be
/// instantiated and returned to the user.
///
/// Sub-classes doesn't necessarily represent a singular WASM type; for example,
/// WASM does not have a char type but we implement a [Char] type to help
/// preserve "native" type information. Without this, [const char*] would only be
/// represented as Pointer<Int64>, and we would have no way of knowing that
/// it can safely be interpreted/converted to a Dart String.
///
///
abstract final class NativeType {}

extension type const Pointer<T extends NativeType>(int addr) implements int {
  Pointer<T> operator +(int byteOffset) => Pointer<T>(this.addr + byteOffset);
  Pointer<U> cast<U extends NativeType>() => this as Pointer<U>;
  void free() {
    _lib._free(this);
  }

  int get address => addr;
}

base class PointerClass<T extends NativeType> extends NativeType {
  final Pointer<T> addr;

  PointerClass(this.addr);

  String get llvmType => '*';
  int size() => 4;

  static PointerClass<PointerClass<T>> stackAlloc<T extends NativeType>(
      int count) {
    return _lib._stackAlloc<T>(4 * count) as PointerClass<PointerClass<T>>;
  }

  PointerClass<T> operator +(int numElements) =>
      PointerClass<T>(this.addr.addr + (numElements * size()) as Pointer<T>);
  PointerClass<U> cast<U extends NativeType>() => this as PointerClass<U>;
}

extension type Null._(NativeType value) implements NativeType {}

Pointer<NativeFunction<T>> addFunction<T>(JSFunction fn, String signature) {
  return _lib.addFunction(fn, signature);
}

extension type Char._(NativeType value) implements NativeType {
  static Pointer<Char> stackAlloc(int count) {
    return Pointer<Char>(_lib._stackAlloc<Char>(4 * count));
  }
}

extension type const Uint32._(NativeType nt) implements NativeType {
  static Pointer<Uint32> stackAlloc(int count) {
    return _lib._stackAlloc<Uint32>(4 * count);
  }
}

extension type const Uint8._(NativeType nt) implements NativeType {
  static Pointer<Uint8> stackAlloc(int count) {
    return _lib._stackAlloc<Uint8>(count);
  }
}

extension type const Int8._(NativeType nt) implements NativeType {
  static Pointer<Int8> stackAlloc(int count) {
    return _lib._stackAlloc<Int8>(count);
  }
}

extension type const Uint16._(NativeType nt) implements NativeType {
  static Pointer<Uint16> stackAlloc(int count) {
    return _lib._stackAlloc<Uint16>(2 * count);
  }
}

extension type const Int16._(NativeType nt) implements NativeType {
  static Pointer<Int16> stackAlloc(int count) {
    return _lib._stackAlloc<Int16>(2 * count);
  }
}

extension type const Int32._(NativeType nt) implements NativeType {
  static Pointer<Int32> stackAlloc(int count) {
    return _lib._stackAlloc<Int32>(4 * count);
  }
}

extension type Int64(NativeType nt) implements NativeType {
  static Pointer<Int64> stackAlloc(int count) {
    return _lib._stackAlloc<Int64>(8 * count);
  }
}
extension type Float32._(NativeType nt) implements NativeType {
  static Pointer<Float32> stackAlloc(int count) {
    return _lib._stackAlloc<Float32>(4 * count);
  }
}
extension type Float64._(NativeType nt) implements NativeType {
  static Pointer<Float64> stackAlloc(int count) {
    return _lib._stackAlloc<Float64>(8 * count);
  }
}
extension type NativeFunction<T>._(NativeType nt) implements NativeType {}
extension type Void._(NativeType nt) implements NativeType {}

Pointer<Never> nullptr = Pointer<Never>(0);

extension PointerPointerClass<T extends NativeType>
    on Pointer<PointerClass<T>> {
  operator [](int i) => this + i;
  void operator []=(int i, Pointer<T> value) {
    _lib.setValue(this + (i * 4), value.addr.toJS, 'i64');
  }
}

extension fncp<T extends NativeType> on void Function(Pointer<T>) {
  Pointer<NativeFunction<void Function(Pointer<T>)>> addFunction() {
    var fnPtr = _lib.addFunction<void Function(Pointer<T>)>(this.toJS, "vp");
    return fnPtr;
  }
}

extension VoidPointerClass on Pointer<Void> {
  String get llvmType => 'v';

  static Pointer<Void> fromAddress(int addr) => Pointer<Void>(addr);
}

extension Int32PointerClass on Pointer<Int32> {
  String get llvmType => 'i32';

  void setValue(int value) {
    _lib.setValue(this, value.toJS, llvmType);
  }

  int getValue() {
    return _lib.getValue(this, llvmType).toDartInt;
  }

  static Pointer<Int32> fromAddress(int addr) => Pointer<Int32>(addr);
}

extension Int64Pointer on Pointer<Int64> {
  String get llvmType => 'i64';

  void setValue(int value) {
    _lib.setValue(this, value.toJS, llvmType);
  }

  int getValue() {
    return _lib.getValue(this, llvmType).toDartInt;
  }

  static Pointer<Int64> fromAddress(int addr) => Pointer<Int64>(addr);
}

extension Float32Pointer on Pointer<Float32> {
  String get llvmType => 'float';

  void setValue(double value) {
    _lib.setValue(this, value.toJS, llvmType);
  }

  double getValue() {
    return _lib.getValue(this, llvmType).toDartDouble;
  }

  double operator [](int i) {
    return _lib.getValue(this + (i * 4), 'f').toDartDouble;
  }

  operator []=(int i, double val) {
    _lib.setValue(this + (i * 4), val.toJS, 'f');
  }

  static Pointer<Float32> fromAddress(int addr) => Pointer<Float32>(addr);
}

extension Float64Pointer on Pointer<Float64> {
  String get llvmType => 'double';

  void setValue(double value) {
    _lib.setValue(this, value.toJS, llvmType);
  }

  double getValue() {
    return _lib.getValue(this, llvmType).toDartDouble;
  }

  static Pointer<Float64> fromAddress(int addr) => Pointer<Float64>(addr);
}

extension StringUtils on String {
  Pointer<Char> toNativeUtf8() {
    var len = _lib._lengthBytesUTF8(this) + 1;
    var ptr = Char.stackAlloc(len);
    _lib._stringToUTF8(this, ptr, len);
    return ptr;
  }
}

extension CharPtr on Pointer<Char> {
  void setValue(String value) {
    var len = _lib._lengthBytesUTF8(value);
    _lib._stringToUTF8(value, this, len);
  }

  String toDartString() {
    return _lib._UTF8ToString(this);
  }

  static Pointer<Char> fromAddress(int addr) => Pointer<Char>(addr);
}

extension DisposePointerClass<T extends NativeType> on Pointer<NativeFunction> {
  void dispose() {
    _lib.removeFunction(this);
  }
}

sealed class Struct extends NativeType {
  final Pointer _address;

  Struct(this._address);

  static T create<T extends Struct>() {
    throw Exception();
  }
}

extension StructPointer<T extends Struct> on T {
  Pointer<T> get address => _address as Pointer<T>;
}

extension type const Array<T extends NativeType>._(
    ({int numElements, Pointer<T> addr}) _) {
  Array<U> cast<U extends NativeType>() => this as Array<U>;

  Uint8List asUint8List() {
    final start = _.addr;
    final end = _.addr.addr + _.numElements;

    return Uint8List.sublistView(
      _lib.HEAPU8.toDart,
      start.addr,
      end,
    );
  }

  void setValue(Uint8List data) {
    _lib.writeArrayToMemory(data.toJS, _.addr);
  }
}

extension ArrayInt32Ext on Array<Int32> {
  double operator [](int i) {
    return _lib.getValue(_.addr + (i * 4), 'double').toDartDouble;
  }
}

extension ArrayFloat32Ext on Array<Float32> {
  double operator [](int i) {
    return _lib.getValue(_.addr + (i * 4), 'double').toDartDouble;
  }
}

extension ArrayFloat64Ext on Array<Float64> {
  double operator [](int i) {
    return _lib.getValue(_.addr + (i * 8), 'double').toDartDouble;
  }

  void operator []=(int i, double v) {
    _lib.setValue(_.addr + (i * 8), v.toJS, 'double');
  }
}

late NativeLibrary _lib;

Pointer<T> malloc<T extends NativeType>(int numBytes) {
  return _lib._malloc<T>(numBytes);
}

Pointer<T> stackAlloc<T extends NativeType>(int numBytes) {
  final ptr = _lib._stackAlloc<T>(numBytes);
  return ptr;
}

void free(Pointer ptr) {
  _lib._free(ptr);
}

@JS('BigInt')
external JSBigInt bigInt(String s);

@JS('BigInt.asUintN')
external JSBigInt bigIntasUintN(int numBits, JSBigInt bi);

extension JSBigIntExtension on JSBigInt {
  BigInt get toDart {
    return BigInt.parse(this.toString());
  }
}

extension BigIntExtension on int {
  JSBigInt get toJSBigInt {
    return bigInt(this.toString());
  }
}

extension DartBigIntExtension on BigInt {
  JSBigInt get toJSBigInt {
    return bigInt(this.toString());
  }
}

extension type NativeLibrary(JSObject _) implements JSObject {
  static NativeLibrary get instance => _lib;

  static void initBindings(String moduleName) {
    var lib = globalContext.getProperty(moduleName.toJS);
    if (lib == null) {
      throw Exception("Failed to find JS module ${moduleName}");
    }
    _lib = lib as NativeLibrary;
  }

  @JS('stackAlloc')
  external Pointer<T> _stackAlloc<T extends NativeType>(int numBytes);

  external Pointer<T> _malloc<T extends NativeType>(int numBytes);

  external void _free(Pointer ptr);

  @JS('stackSave')
  external Pointer<Void> stackSave();

  @JS('stackRestore')
  external void stackRestore(Pointer<Void> ptr);

  @JS('getValue')
  external JSBigInt getValueBigInt(Pointer addr, String llvmType);
  external JSNumber getValue(Pointer addr, String llvmType);
  external void setValue(Pointer addr, JSNumber value, String llvmType);

  @JS("lengthBytesUTF8")
  external int _lengthBytesUTF8(String str);

  @JS("UTF8ToString")
  external String _UTF8ToString(Pointer<Char> ptr);

  @JS("stringToUTF8")
  external void _stringToUTF8(
      String str, Pointer<Char> ptr, int maxBytesToWrite);

  external void writeArrayToMemory(JSUint8Array data, Pointer ptr);

  external Pointer<NativeFunction<T>> addFunction<T>(
      JSFunction f, String signature);
  external void removeFunction<T>(Pointer<NativeFunction<T>> f);
  external JSUint8Array get HEAPU8;
  external JSFloat32Array get HEAPF32;

  external Pointer<Int32> _GLOBALINT;
  external void _write(
    Pointer<Int32> out,
  );
  external int _sum(
    int a,
    int b,
  );
  external INTTYPE _sum_with_typedef(
    INTTYPE a,
    INTTYPE b,
  );
  external int _subtract(
    Pointer<Int32> a,
    int b,
  );
  external Pointer<Int32> _multiply(
    int a,
    int b,
  );
  external Pointer<Float32> _divide(
    int a,
    int b,
  );
  external Pointer<Float64> _divide_precision(
    Pointer<Float32> a,
    Pointer<Float32> b,
  );
  external void _accept_fn_typedef_arg(
    FunctionTypedef arg,
  );
  external FunctionTypedef _return_fn_typedef();
  external void _uint8_tptr_(
    Pointer<Uint8> data,
  );
  external void _int8_tptr_method(
    Pointer<Int8> data,
  );
  external Pointer<Float64> _return_array();
  external Pointer<Void> _return_void_ptr();
  external void _accept_void_ptr(
    Pointer<Void> arg,
  );
  external int _struct_as_argument(
    Pointer<double3> vectorPtr,
  );
  external Pointer<MyStruct> _return_struct_ptr();
  external void _accept_struct_ptr(
    Pointer<MyStruct> arg,
  );
  external void _accept_struct_with_array(
    Pointer<StructWithArray> argPtr,
  );
  external void _return_struct_with_array_by_value(
    Pointer<StructWithArray> StructWithArray_out,
  );
  external void _return_struct_by_value(
    Pointer<MyStruct> MyStruct_out,
    double a,
    Pointer<Char> b,
  );
  external Pointer<self.PointerClass<Int32>> _ptr_ptr(
    Pointer<self.PointerClass<Int32>> a,
    Pointer<self.PointerClass<Int32>> b,
  );
  external Pointer<Char> _copy_string(
    Pointer<Char> instr,
  );
  external void _accept_fn_pointer_with_no_args(
    Pointer<self.NativeFunction<void Function()>> callback,
  );
  external void _accept_fn_pointer_with_primitive_args(
    Pointer<self.NativeFunction<void Function(int arg)>> callback,
  );
  external void _accept_fn_pointer_with_ptr_args(
    Pointer<self.NativeFunction<void Function(PointerClass<MyStruct> arg)>>
        callback,
  );
  external void _accept_opaque_struct_ptr(
    Pointer<MyOpaqueStruct> ptr,
  );
  external int _returns_bool();
  external int _return_enum();
  external int _accept_enum(
    int val,
  );
  external int _return_enum_as_int();
  external JSBigInt _bigint_method(
    JSBigInt number,
  );
  external size_t _size_tmethod(
    size_t number,
  );
}

BigInt get GLOBALINT {
  final value = _lib.getValueBigInt(_lib._GLOBALINT, "i64");
  return bigIntasUintN(64, value).toDart;
}

void write(
  self.Pointer<Int32> out,
) {
  final result = _lib._write(out);
  return result;
}

int sum(
  int a,
  int b,
) {
  final result = _lib._sum(a, b);
  return result;
}

DartINTTYPE sum_with_typedef(
  DartINTTYPE a,
  DartINTTYPE b,
) {
  final result = _lib._sum_with_typedef(a, b);
  return result;
}

int subtract(
  self.Pointer<Int32> a,
  int b,
) {
  final result = _lib._subtract(a, b);
  return result;
}

self.Pointer<Int32> multiply(
  int a,
  int b,
) {
  final result = _lib._multiply(a, b);
  return self.Pointer<Int32>(result);
}

self.Pointer<Float32> divide(
  int a,
  int b,
) {
  final result = _lib._divide(a, b);
  return self.Pointer<Float32>(result);
}

self.Pointer<Float64> divide_precision(
  self.Pointer<Float32> a,
  self.Pointer<Float32> b,
) {
  final result = _lib._divide_precision(a, b);
  return self.Pointer<Float64>(result);
}

void accept_fn_typedef_arg(
  DartFunctionTypedef arg,
) {
  final result = _lib._accept_fn_typedef_arg(
      arg as Pointer<self.NativeFunction<FunctionTypedefFunction>>);
  return result;
}

DartFunctionTypedef return_fn_typedef() {
  final result = _lib._return_fn_typedef();
  return DartFunctionTypedef(result);
}

void uint8_tptr_(
  self.Pointer<Uint8> data,
) {
  final result = _lib._uint8_tptr_(data);
  return result;
}

void int8_tptr_method(
  self.Pointer<Int8> data,
) {
  final result = _lib._int8_tptr_method(data);
  return result;
}

self.Pointer<Float64> return_array() {
  final result = _lib._return_array();
  return self.Pointer<Float64>(result);
}

self.Pointer<Void> return_void_ptr() {
  final result = _lib._return_void_ptr();
  return self.Pointer<Void>(result);
}

void accept_void_ptr(
  self.Pointer<Void> arg,
) {
  final result = _lib._accept_void_ptr(arg);
  return result;
}

int struct_as_argument(
  double3 vector,
) {
  final vectorPtr = vector._address;
  final result = _lib._struct_as_argument(vectorPtr.cast());
  return result;
}

self.Pointer<MyStruct> return_struct_ptr() {
  final result = _lib._return_struct_ptr();
  return self.Pointer<MyStruct>(result);
}

void accept_struct_ptr(
  self.Pointer<MyStruct> arg,
) {
  final result = _lib._accept_struct_ptr(arg.cast());
  return result;
}

void accept_struct_with_array(
  StructWithArray arg,
) {
  final argPtr = arg._address;
  final result = _lib._accept_struct_with_array(argPtr.cast());
  return result;
}

StructWithArray return_struct_with_array_by_value() {
  final StructWithArray_out = StructWithArray.stackAlloc();
  final result =
      _lib._return_struct_with_array_by_value(StructWithArray_out.cast());
  return StructWithArray_out.toDart();
}

MyStruct return_struct_by_value(
  double a,
  self.Pointer<Char> b,
) {
  final MyStruct_out = MyStruct.stackAlloc();
  final result = _lib._return_struct_by_value(MyStruct_out.cast(), a, b);
  return MyStruct_out.toDart();
}

self.Pointer<self.PointerClass<Int32>> ptr_ptr(
  self.Pointer<self.PointerClass<Int32>> a,
  self.Pointer<self.PointerClass<Int32>> b,
) {
  final result = _lib._ptr_ptr(a, b);
  return self.Pointer<self.PointerClass<Int32>>(result);
}

self.Pointer<Char> copy_string(
  self.Pointer<Char> instr,
) {
  final result = _lib._copy_string(instr);
  return self.Pointer<Char>(result);
}

void accept_fn_pointer_with_no_args(
  self.Pointer<self.NativeFunction<void Function()>> callback,
) {
  final result = _lib._accept_fn_pointer_with_no_args(callback.cast());
  return result;
}

void accept_fn_pointer_with_primitive_args(
  self.Pointer<self.NativeFunction<void Function(int arg)>> callback,
) {
  final result = _lib._accept_fn_pointer_with_primitive_args(callback.cast());
  return result;
}

void accept_fn_pointer_with_ptr_args(
  self.Pointer<self.NativeFunction<void Function(Pointer<MyStruct> arg)>>
      callback,
) {
  final result = _lib._accept_fn_pointer_with_ptr_args(callback.cast());
  return result;
}

void accept_opaque_struct_ptr(
  self.Pointer<MyOpaqueStruct> ptr,
) {
  final result = _lib._accept_opaque_struct_ptr(ptr.cast());
  return result;
}

bool returns_bool() {
  final result = _lib._returns_bool();
  return result == 1;
}

MyEnum return_enum() {
  final result = _lib._return_enum();
  return MyEnum.fromValue(result);
}

int accept_enum(
  MyEnum val,
) {
  final result = _lib._accept_enum(val.value);
  return result;
}

int return_enum_as_int() {
  final result = _lib._return_enum_as_int();
  return result;
}

BigInt bigint_method(
  BigInt number,
) {
  final result = _lib._bigint_method(number.toJSBigInt);
  return bigIntasUintN(64, result).toDart;
}

Dart__darwin_size_t size_tmethod(
  Dart__darwin_size_t number,
) {
  final result = _lib._size_tmethod(number);
  return result;
}

typedef INTTYPE = int;
typedef DartINTTYPE = int;
typedef FunctionTypedef = Pointer<self.NativeFunction<FunctionTypedefFunction>>;
typedef DartFunctionTypedef
    = self.Pointer<self.NativeFunction<FunctionTypedefFunction>>;
typedef FunctionTypedefFunction = void Function(Pointer<Void> owner);
typedef DartFunctionTypedefFunction = void Function(self.Pointer<Void> owner);

extension double3Ext on Pointer<double3> {
  double3 toDart() {
    return double3(this);
  }
}

final class double3 extends self.Struct {
  double get x {
    final value = _lib.getValue(this._address + 0, 'double').toDartDouble;
    return value;
  }

  set x(double val) {
    _lib.setValue(this._address + 0, val.toJS, 'double');
  }

  double get y {
    final value = _lib.getValue(this._address + 8, 'double').toDartDouble;
    return value;
  }

  set y(double val) {
    _lib.setValue(this._address + 8, val.toJS, 'double');
  }

  double get z {
    final value = _lib.getValue(this._address + 16, 'double').toDartDouble;
    return value;
  }

  set z(double val) {
    _lib.setValue(this._address + 16, val.toJS, 'double');
  }

  double3(super._address);

  static Pointer<double3> stackAlloc() {
    return Pointer<double3>(_lib._stackAlloc<double3>(24));
  }
}

extension MyStructExt on Pointer<MyStruct> {
  MyStruct toDart() {
    return MyStruct(this);
  }
}

final class MyStruct extends self.Struct {
  double get a {
    final value = _lib.getValue(this._address + 0, 'float').toDartDouble;
    return value;
  }

  set a(double val) {
    _lib.setValue(this._address + 0, val.toJS, 'float');
  }

  self.Pointer<Char> get b {
    final value = _lib.getValue(this._address + 4, '*');
    return self.Pointer<Char>(value.toDartInt);
  }

  set b(self.Pointer<Char> val) {
    _lib.setValue(this._address + 4, val.toJS, '*');
  }

  int get c {
    final value = _lib.getValue(this._address + 8, 'i32').toDartInt;
    return value;
  }

  set c(int val) {
    _lib.setValue(this._address + 8, val.toJS, 'i32');
  }

  MyStruct(super._address);

  static Pointer<MyStruct> stackAlloc() {
    return Pointer<MyStruct>(_lib._stackAlloc<MyStruct>(12));
  }
}

extension StructWithArrayExt on Pointer<StructWithArray> {
  StructWithArray toDart() {
    return StructWithArray(this);
  }
}

final class StructWithArray extends self.Struct {
  Array<Float64> get array1 {
    final value = _lib.getValue(this._address + 0, '*');
    return Array<Float64>._(
        (numElements: 2, addr: Pointer<Float64>(this._address + 0)));
  }

  set array1(Array<Float64> val) {
    _lib.setValue(this._address + 0, val._.addr.addr.toJS, '*');
  }

  Array<Float64> get array2 {
    final value = _lib.getValue(this._address + 16, '*');
    return Array<Float64>._(
        (numElements: 3, addr: Pointer<Float64>(this._address + 16)));
  }

  set array2(Array<Float64> val) {
    _lib.setValue(this._address + 16, val._.addr.addr.toJS, '*');
  }

  StructWithArray(super._address);

  static Pointer<StructWithArray> stackAlloc() {
    return Pointer<StructWithArray>(_lib._stackAlloc<StructWithArray>(40));
  }
}

extension MyOpaqueStructExt on Pointer<MyOpaqueStruct> {
  MyOpaqueStruct toDart() {
    return MyOpaqueStruct(this);
  }
}

final class MyOpaqueStruct extends self.Struct {
  MyOpaqueStruct(super._address);

  static Pointer<MyOpaqueStruct> stackAlloc() {
    return Pointer<MyOpaqueStruct>(_lib._stackAlloc<MyOpaqueStruct>(0));
  }
}

enum MyEnum {
  ENUM_VAL1(0),
  ENUM_VAL2(1);

  final int value;
  const MyEnum(this.value);

  static MyEnum fromValue(int value) => switch (value) {
        0 => ENUM_VAL1,
        1 => ENUM_VAL2,
        _ => throw ArgumentError("Unknown value for MyEnum: $value"),
      };
}

sealed class MyEnumAsInt {
  static const ENUM_AS_INT_VAL1 = 0;
  static const ENUM_AS_INT_VAL2 = 1;
}

typedef size_t = __darwin_size_t;
typedef __darwin_size_t = int;
typedef Dart__darwin_size_t = int;

const int __has_safe_buffers = 0;

const int __DARWIN_ONLY_64_BIT_INO_T = 1;

const int __DARWIN_ONLY_UNIX_CONFORMANCE = 1;

const int __DARWIN_ONLY_VERS_1050 = 1;

const int __DARWIN_UNIX03 = 1;

const int __DARWIN_64_BIT_INO_T = 1;

const int __DARWIN_VERS_1050 = 1;

const int __DARWIN_NON_CANCELABLE = 0;

const String __DARWIN_SUF_EXTSN = '\$DARWIN_EXTSN';

const int __DARWIN_C_ANSI = 4096;

const int __DARWIN_C_FULL = 900000;

const int __DARWIN_C_LEVEL = 900000;

const int __STDC_WANT_LIB_EXT1__ = 1;

const int __DARWIN_NO_LONG_LONG = 0;

const int _DARWIN_FEATURE_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_64_BIT_INODE = 1;

const int _DARWIN_FEATURE_ONLY_VERS_1050 = 1;

const int _DARWIN_FEATURE_ONLY_UNIX_CONFORMANCE = 1;

const int _DARWIN_FEATURE_UNIX_CONFORMANCE = 3;

const int __has_ptrcheck = 0;

const int __DARWIN_NULL = 0;

const int __PTHREAD_SIZE__ = 8176;

const int __PTHREAD_ATTR_SIZE__ = 56;

const int __PTHREAD_MUTEXATTR_SIZE__ = 8;

const int __PTHREAD_MUTEX_SIZE__ = 56;

const int __PTHREAD_CONDATTR_SIZE__ = 8;

const int __PTHREAD_COND_SIZE__ = 40;

const int __PTHREAD_ONCE_SIZE__ = 8;

const int __PTHREAD_RWLOCK_SIZE__ = 192;

const int __PTHREAD_RWLOCKATTR_SIZE__ = 16;

const int __DARWIN_WCHAR_MAX = 2147483647;

const int __DARWIN_WCHAR_MIN = -2147483648;

const int __DARWIN_WEOF = -1;

const int _FORTIFY_SOURCE = 2;

const int NULL = 0;

const int USER_ADDR_NULL = 0;

const int __WORDSIZE = 64;

const int INT8_MAX = 127;

const int INT16_MAX = 32767;

const int INT32_MAX = 2147483647;

const int INT64_MAX = 9223372036854775807;

const int INT8_MIN = -128;

const int INT16_MIN = -32768;

const int INT32_MIN = -2147483648;

const int INT64_MIN = -9223372036854775808;

const int UINT8_MAX = 255;

const int UINT16_MAX = 65535;

const int UINT32_MAX = 4294967295;

const int UINT64_MAX = -1;

const int INT_LEAST8_MIN = -128;

const int INT_LEAST16_MIN = -32768;

const int INT_LEAST32_MIN = -2147483648;

const int INT_LEAST64_MIN = -9223372036854775808;

const int INT_LEAST8_MAX = 127;

const int INT_LEAST16_MAX = 32767;

const int INT_LEAST32_MAX = 2147483647;

const int INT_LEAST64_MAX = 9223372036854775807;

const int UINT_LEAST8_MAX = 255;

const int UINT_LEAST16_MAX = 65535;

const int UINT_LEAST32_MAX = 4294967295;

const int UINT_LEAST64_MAX = -1;

const int INT_FAST8_MIN = -128;

const int INT_FAST16_MIN = -32768;

const int INT_FAST32_MIN = -2147483648;

const int INT_FAST64_MIN = -9223372036854775808;

const int INT_FAST8_MAX = 127;

const int INT_FAST16_MAX = 32767;

const int INT_FAST32_MAX = 2147483647;

const int INT_FAST64_MAX = 9223372036854775807;

const int UINT_FAST8_MAX = 255;

const int UINT_FAST16_MAX = 65535;

const int UINT_FAST32_MAX = 4294967295;

const int UINT_FAST64_MAX = -1;

const int INTPTR_MAX = 9223372036854775807;

const int INTPTR_MIN = -9223372036854775808;

const int UINTPTR_MAX = -1;

const int INTMAX_MAX = 9223372036854775807;

const int UINTMAX_MAX = -1;

const int INTMAX_MIN = -9223372036854775808;

const int PTRDIFF_MIN = -9223372036854775808;

const int PTRDIFF_MAX = 9223372036854775807;

const int SIZE_MAX = -1;

const int RSIZE_MAX = 9223372036854775807;

const int WCHAR_MAX = 2147483647;

const int WCHAR_MIN = -2147483648;

const int WINT_MIN = -2147483648;

const int WINT_MAX = 2147483647;

const int SIG_ATOMIC_MIN = -2147483648;

const int SIG_ATOMIC_MAX = 2147483647;

const int __bool_true_false_are_defined = 1;

extension NativeFunctionPointer0<T extends NativeType> on void Function() {
  // orignal type void Function() void Function() dart type void Function()

  Pointer<NativeFunction<void Function()>> addFunction() {
    return Pointer<NativeFunction<void Function()>>(
            _lib.addFunction<void Function()>(this.toJS, 'v'))
        .cast();
  }
}

extension NativeFunctionPointer1<T extends NativeType> on void Function(
    int arg) {
  // orignal type void Function(int arg) void Function(int arg) dart type void Function(int arg)

  Pointer<NativeFunction<void Function(int arg)>> addFunction() {
    return Pointer<NativeFunction<void Function(int arg)>>(
            _lib.addFunction<void Function(int arg)>(this.toJS, 'vi'))
        .cast();
  }
}

extension NativeFunctionPointer2<T extends NativeType> on void Function(
    self.Pointer<MyStruct> arg) {
  // orignal type void Function(self.Pointer<MyStruct> arg) void Function(Pointer<MyStruct> arg) dart type void Function(self.Pointer<MyStruct> arg)

  Pointer<NativeFunction<void Function(self.Pointer<MyStruct> arg)>>
      addFunction() {
    return Pointer<NativeFunction<void Function(self.Pointer<MyStruct> arg)>>(
            _lib.addFunction<void Function(self.Pointer<MyStruct> arg)>(
                this.toJS, 'vp'))
        .cast();
  }
}
